# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "August Penguin 2017"
email: "august@hamakor.org.il"
description: "The annual free and open source software convention in Israel"
baseurl: "/AugustPenguin2017"
url: "http://hamakor.github.io" #TODO - update to our domain
permalink: "/blog/:title"
#TODO google analytics
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "night46.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Hamakor"
organizerAlternateName: "Hamakor Foundation"
organizerDescription: "The Israeli Society for open source and free software."
organizerEmail: "august@hamakor.org.il"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.hamakor.org.il/"

# Head
metaKeywords: "hamakor, augustpenguin, august penguin, open source, foss"
#TODO tweeter account
twitterAccount: "@augustpenguin"
socialImageSrcGooglePlus: "/img/seo/cyborg-penguin.png"
socialImageSrcTwitter: "/img/seo/cyborg-penguin.png"
socialImageSrcFacebook: "/img/seo/cyborg-penguin.png"

# Documents
#TODO google form call for papers short link
c4pUrl: "http://bit.ly/dfua-c4p" 
#TODO sponsorship PDF
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 # - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 # - {permalink: "/schedule/", text: "Schedule"}
 # - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
#TODO
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
#TODO
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "August Penguin <typeout> 2017"
#TODO update date
eventDate: "August, 2017"
typeoutTextValues: '"", "Conf", "Season", "Israel"'
typeoutFallback: "Season"
heroButtons:
#TODO
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About August Penguin"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest annual free and open source software convention in Israel borught to you with love from HAMAKOR! Awesome speakers and lots of fun!" }
 - {title: "Tracks", image: "tracks.jpg", text: "Two Full-days of a lof of interesting tracks all revolving Open Source. Come and enjoy your favourite technology!" }
 - {title: "Community", image: "community.jpg", text: "Come and be a part of the community, share your knowledge, make frinds, be a part of the movement that kames Open Source great!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Open Source anything"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Tel-Aviv University"
#eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "TBD"
eventAddressLocality: "Tel-Aviv"
#eventAddressLocalityRegion: "Lvivska"
#eventPostalCode: "79000"
eventAddressCountry: "Israel"
eventStartTime: "2017-08-1T09:00"
eventDoorTime: "08:00"
eventEndTime: "2017-08-2T20:00"
eventPlaceCoordinates: "32.1133141, 34.802199"
mapCenterCoordinates: "32.1133141, 34.802199"
mapMobileCenterCoordinates: "32.1133141, 34.802199"

# Venue Block
venueBlockTitle: "TAU"
venueBigImage: "tau0.jpg"
venueSmallImage1: "tau1.jpg"
venueSmallImage2: "tau2.jpg"
venueTitle: "Tel-Aviv University"
venueFeatures: ["Commited to Open Source", "Luxurious and advanced", "Located directly in beutiful location"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "augustpenguin"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of Julay. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and fun."
ticketsOffers:
 -
  name: "Early Bird"
  price: "40"
  priceCurrency: "NIS"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Registered members enter for free", "Join or Buy a ticket", "Waiting to see you!"]
  validFrom: "2017-05-01T10:00"
  validThrough: "2017-07-1T23:59"
 -
  name: "Last Chance"
  price: "50"
  priceCurrency: "NIS"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Registered members enter for free", "Join or Buy a ticket", "Waiting to see you!"]
  validFrom: "2017-07-01T00:00"
  validThrough: "2017-07-30T23:59"
  disabled: true
 -
  name: "Student"
  price: "30"
  priceCurrency: "NIS"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Registered members enter for free", "Join or Buy a ticket", "Waiting to see you!"]
  validFrom: "2017-07-01T10:00"
  validThrough: "2017-07-30T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
#TODO social media links
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://hamakor.org.il", text: "Hamakor"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:august@hamakor.org.il", text: "august@hamakor.org.il"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "August Penguin has became the largest Open Source community convention in Isarel, thoughe luckly there are plany Open Source related meetups and groups. Hamakor, the Israeli Society for Free and Open Source Software initiated August Penguin back in 2002 and ever since we strive to create a home for all Open Source groups and enthusiasts. This year we have been working hard with the help of a lot of volunteers to make this one the best August Penguin that ever was!  -- See you there! "

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "32.1133141, 34.802199"
logisticsMapMobileCenterCoordinates: "32.1133141, 34.802199"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Tel-Aviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is about 15 min dirve. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.iaa.gov.il/tlvflights/">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Tel-Aviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Tel-Aviv.'}
 - {title: "Hotels", information: 'Tel-Aviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions? - For any assistance and information lease do contact us"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
